#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true


  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = 'p:os'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '


  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }} {{else}}{{.UserName}}{{ end }}'


  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:closer'
    template = " ❯ "


  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:mauve'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      folder_icon = "..."
      home_icon = '~'
      style = 'agnoster_short'
      max_depth = 3

  [[blocks.segments]]
    # type = 'git'
    # style = 'plain'
    # foreground = 'p:grey'
    # background = 'transparent'
    # template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:sapphire>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    #
    # [blocks.segments.properties]
    #   # branch_icon = ''
    #   commit_icon = '@'
    #   fetch_status = true
type = "git"
style = "plain"
powerline_symbol = ""
foreground = "p:grey"
# background = "#ffeb3b"
background = "transparent"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:peach{{ end }}",
  "{{ if gt .Ahead 0 }}p:mauve{{ end }}",
  "{{ if gt .Behind 0 }}p:mauve{{ end }}"
]
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
# template = {{.Working.Changed}}

[properties]
fetch_status = true
fetch_upstream_icon = true


[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:peach"
    # background = "p:blue"
    template = "{{ if .Error }}{{ .Error }}{{ else }}  @ {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Major }}.{{ .Minor }}{{ end }}"


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:lavender{{end}}",
    ]
    background = 'transparent'
    template = '󰘧 ❯'


# [secondary_prompt]
#   foreground = 'magenta'
#   background = 'transparent'
#   template = '❯❯ '


[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'
  green = "#a6e3a1"
  red = "#f38ba8"
  peach = "#fab387"
  flamingo = "#f2cdcd"
  yellow = "#f9e2af"
  sapphire = "#74c7ec"
  mauve = "#cba6f7"
  grey = "#6c7086"
