#!/usr/bin/env bash

# Most use dirs navigation
alias dev='cd ~/dev'

# Copy current directory to clipboard
alias cpwd="pwd | xclip -selection clipboard"   

# Open nvim
alias nv="nvim"
alias vim="nvim"

# CD to common directories
alias notes="cd ~/vaults/notes && nv ./Home.md"
alias dotfiles="cd ~/dotfiles"


# ls customization
alias ls="eza --color=always --git --no-filesize --icons=always --no-time --no-user --no-permissions"
alias la="eza -a --color=always --git --no-filesize --icons=always --no-time --no-user --no-permissions"
alias tree="eza --color=always --git --no-filesize --icons=always --no-time --no-user --no-permissions --tree"

# better cat
alias cat="bat"

# better cd already on .zshrc
# alias cd="z"
alias update="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean"



# Show whole history
alias history="history 1"

# grep settings
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# Search history
alias shis="history | grep" 

# Conda activate
alias ca="conda activate"


# Lazy git
alias lg="lazygit"
