#!/usr/bin/env bash
# FNM_PATH="/home/pedro/.local/share/fnm"
# if [ -d "$FNM_PATH" ]; then
#   export PATH="/home/pedro/.local/share/fnm:$PATH"
#   eval "`fnm env`"
# fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm 

source "$HOME/.rye/env"

__conda_setup="$('/home/pedro/miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/pedro/miniconda/etc/profile.d/conda.sh" ]; then
        . "/home/pedro/miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/pedro/miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
