# Simple clean animations for Hyprland

animations {
  enabled = yes

  # General animation speed
  bezier = smooth, 0.05, 0.9, 0.1, 1.0
  animation = windows, 1, 5, smooth, slide
  animation = windowsOut, 1, 5, smooth, slide
  animation = border, 1, 5, smooth
  animation = fade, 1, 5, smooth
  animation = workspaces, 1, 5, smooth, slide
}

decoration {
    rounding = 10           # corner radius in pixels
}