# Unbind default omarchy keybindings
unbind = SUPER, W
unbind = SUPER, T
unbind = SUPER, F
unbind = SUPER, O
unbind = SUPER, V
unbind = SUPER, S
unbind = SUPER, C
unbind = SUPER, N
unbind = ALT, N
unbind = SUPER CTRL, Z

bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard
# bindd = SUPER, O, Launch apps, exec, omarchy-launch-walker


# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

# Also Start terminal and run fast fetch on it
bindd = SUPER, return, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)" 
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-webapp "https://music.youtube.com/"
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, T, Todoist, exec, todoist
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER ALT, L, LocalSend, exec, localsend
bindd = SUPER, S, Steam, exec, uwsm app -- steam


bindd = SUPER CTRL, Z, Toggle nightlight, exec, nightshift-toggle
bindd = SUPER, C, Claude, exec, omarchy-launch-webapp "https://claude.ai/"
bindd = SUPER ALT, C, Claude Code, exec, uwsm app -- xdg-terminal-exec claude
bindd = SUPER SHIFT, O, Claude in Notes, exec, uwsm app -- xdg-terminal-exec --dir=/home/pedro/notes claude
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER, W, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER, E, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/"
bindd = SUPER, Q, Close active window, killactive,



