# Custom window rules (override defaults)

# Make Steam tiled instead of floating
windowrule = tile on, match:class steam

# Remove transparency from Obsidian
windowrule = tag -default-opacity, match:class obsidian
windowrule = opacity 1 1, match:class obsidian

# Make terminals fully opaque (default is 0.97 0.9)
windowrule = opacity 1 1, match:tag terminal
